# Generated by Django 5.2.4 on 2025-08-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Honda', 'Honda'), ('BMW', 'BMW'), ('Mercedes', 'Mercedes'), ('Nissan', 'Nissan'), ('Hyundai', 'Hyundai')], default='Toyota', max_length=50),
        ),
        migrations.AlterField(
            model_name='rental',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
