# Generated by Django 5.2.4 on 2025-08-03 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0002_alter_car_brand_alter_rental_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_agent': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_rentals', to=settings.AUTH_USER_MODEL),
        ),
    ]
