# Generated by Django 5.2.4 on 2025-08-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentcars", "0003_alter_rental_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="license_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="customer_licenses/"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="customer_profiles/"
            ),
        ),
    ]
