# Generated by Django 5.2.4 on 2025-08-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentcars", "0004_customer_license_image_customer_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="exterior_image",
            field=models.ImageField(blank=True, null=True, upload_to="car_images/"),
        ),
        migrations.AddField(
            model_name="car",
            name="interior_image",
            field=models.ImageField(blank=True, null=True, upload_to="car_images/"),
        ),
        migrations.AddField(
            model_name="car",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to="car_images/"),
        ),
    ]
