# Generated by Django 5.2.4 on 2025-08-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentcars", "0006_maintenance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="brand",
            field=models.CharField(
                choices=[
                    ("Audi", "Audi"),
                    ("BMW", "BMW"),
                    ("Chevrolet", "Chevrolet"),
                    ("Ford", "Ford"),
                    ("Honda", "Honda"),
                    ("Hyundai", "Hyundai"),
                    ("Infiniti", "Infiniti"),
                    ("Jaguar", "Jaguar"),
                    ("Kia", "Kia"),
                    ("Land Rover", "Land Rover"),
                    ("Lexus", "Lexus"),
                    ("Mazda", "Mazda"),
                    ("Mercedes", "Mercedes"),
                    ("Mitsubishi", "Mitsubishi"),
                    ("Nissan", "Nissan"),
                    ("Peugeot", "Peugeot"),
                    ("Porsche", "Porsche"),
                    ("Renault", "Renault"),
                    ("Subaru", "Subaru"),
                    ("Tesla", "Tesla"),
                    ("Toyota", "Toyota"),
                    ("Volkswagen", "Volkswagen"),
                    ("Volvo", "Volvo"),
                ],
                default="Toyota",
                max_length=50,
            ),
        ),
    ]
