version: "3.9"

services:
  web:
    build: .
    image: renty-backend:latest
    container_name: renty-web
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=carrental.settings
      - PYTHONUNBUFFERED=1
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    restart: unless-stopped
